### ISSUE TITLE
Put on PyPI

### ISSUE THREAD

**Issue by samjett247** [BIDS/colormap#11]
Is there any particular reason this repo hasn't been put into PyPI? Would love to be able to import without copy/pasting the colormaps.py file into my repos. Happy to help build a `setup.py` if there is interest in posting it on PyPI.

**Comment by stefanv** [comment]
viscm is on pypi, and the colormaps are part of Matplotlib.  Do you need them available in a different form?  The data files you can use directly in your application as you see fit.

**Comment by samjett247** [comment]
I wasn't able to pull and use the **parula** map from viscm nor from matplotlib. I just wanted to parula colormap in a matplotlib amenable form. I suppose that a single colormap is a pretty small reason to put something on PyPI, since I think most other colormaps are in matplotlib. I may fork it and do it anyway though :)

**Comment by stefanv** [comment]
The Mathworks claims copyright over that colormap, so we cannot distribute it.
