### ISSUE TITLE
Are viridis and related maps published as Python module?

### ISSUE THREAD

**Issue by Tronic** [BIDS/colormap#12]
Is there any pip installable source for these colormaps? Including colormaps.py from here, or extracting them from matplotlib seem suboptimal. It doesn't seem to be specified anywhere, but I gather that colormaps.py arrays are in sRGB1 (non-linear), is this correct?

Also, are the equations (code) used for creating the maps available anywhere?

**Comment by njsmith** [comment]
I'm not aware of any standalone pip packages, no. You could make one if you want?

> It doesn't seem to be specified anywhere, but I gather that colormaps.py arrays are in sRGB1 (non-linear), is this correct?

Yes, the values in `colormaps.py` are sRGB1.

> Also, are the equations (code) used for creating the maps available anywhere?

The individual files contain the spline parameters that were used to create the colormaps, e.g. these are for viridis:

https://github.com/BIDS/colormap/blob/bc549477db0c12b54a5928087552ad2cf274980f/option_d.py#L6-L9

The creation involved drawing curves in an interactive tool though so there isn't really any useful "equation".

**Comment by Tronic** [comment]
I suppose that these parameters would have to be plugged into some spline equation (one that produces equidistant points along the curve) and then through colorspacious conversion from CAM02-UCS to the desired space? Implementation of this would've been nice to have but doesn't seem to be worth the effort to construct it from so many pieces.

**Comment by njsmith** [comment]
The code's all available in viscm, but I don't think it's really useful for anything... If you want to make a new colormap, you can use viscm; if you just want the existing colormaps, the final sRGB1 points contain all the information there is.
