### ISSUE TITLE
Pack very large

### ISSUE THREAD

**Issue by OceanWolf** [BIDS/colormap#2]
Just tried cloning this repo and it took much longer then expected owing to a large pack size... i.e. 17Mb 99% stored in `.git/objects/pack/pack-6b24ce3d7a0ffb8b614f9cdcc5e68dfd610187a9.pack`, this seems crazy for just a few short text files and a handful of commits...

**Comment by QuLogic** [comment]
It's probably because of the `gh-pages` branch (which is more than just a few text files)...

**Comment by njsmith** [comment]
Yeah, this repo is also the website, including the example images :-)
