### ISSUE TITLE
Gamut slice rendered incorrectly in editor

### ISSUE THREAD

**Issue by ccopsey** [BIDS/colormap#4]
On a fresh install of WinPython-64bit-3.4.3.4 and viscm:

In the editor the gamut slice is rendered with blue and red in the correct place, but green and pink inverted (i.e. x & y interchanged).  The spline and colourmap therefore do not correspond to the slice.  The following is a replication of the example at the bottom of http://bids.github.io/colormap/.

![error](https://cloud.githubusercontent.com/assets/150505/8616767/b7344e0e-26f5-11e5-8f2c-1127523541a0.png)

**Comment by njsmith** [comment]
Thanks for the report, and sorry I missed it before... apparently I had github notifications turned off for this repo; no idea how that happened!

This should be fixed as of a few months ago.
