### ISSUE TITLE
Don't tell people that we have put parula under CC0

### ISSUE THREAD

**Issue by nzjrs** [BIDS/colormap#9]
SSIA. It strikes me as implausible that MATLAB owns the exclusive use of an array of numbers, and even more implausible that if an perceptually very similar colormap to parula were to live in this repository (so as to be made from non-identical RGB values) whether that would be covered by any claimed ownership over the 'original' parula.

What do the authors believe on this topic?
Is the parula.py file here a recreation of the parula colormap from MATLAB by independent means? (I can't check I don't have a MATLAB license)

**Comment by njsmith** [comment]
The `parula.py` here is the one from MATLAB, so whatever intellectual property rights the MathWorks has over the parula colormap – if any – apply to `parula.py` as well.

Last time we asked, they *did* claim that they have some kind of intellectual property rights over parula. I'm not convinced they're correct about that, but I'm not a lawyer, and I haven't talked to any lawyers. Pretty much all intellectual property rights are about "the exclusive use of an array of numbers" (what else is a DVD, an MP3, a JPG, etc.?), so *that* hardly proves anything. If you need legal advice, talk to a lawyer.

Anyway, viridis is better, so who cares about parula anyway 😜

**Comment by nzjrs** [comment]
> The parula.py here is the one from MATLAB, so whatever intellectual property rights the MathWorks 
> has over the parula colormap – if any – apply to parula.py as well.

Is this also true for `fake_parula.py` too?

Not asking about the license necessary (WANAL) - but the origin of the numbers.

**Comment by njsmith** [comment]
Oh, `fake_parula.py` is some silliness we made up from scratch, but trying to match parula. So maybe it's a derived work in the copyright sense, maybe not.

**Comment by nzjrs** [comment]
OK, thanks for your clarification.

FWIW you might want to put a note somewhere that `parula.py` is literally copy-pasta from MATLAB sources. I've seen enough people copying `parula.py` into their projects under the understanding that `CC0` and the note at the top of https://bids.github.io/colormap/ applies to `parula.py` and that it is not connected to the MATLAB implementation in any concrete licesnse/copyright way (again, WANAL, but best to help people not do the wrongest thing).

**Comment by njsmith** [comment]
Hmm, fair enough.
